# Generated by Django 5.2.6 on 2025-09-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptivequestion',
            name='level',
            field=models.IntegerField(default=0, help_text='Difficulty level (0=beginner, 1=intermediate, 2=advanced, etc.)'),
        ),
        migrations.AddIndex(
            model_name='adaptivequestion',
            index=models.Index(fields=['skill_id', 'level'], name='adaptive_qu_skill_i_3d0fcb_idx'),
        ),
    ]
