# Generated by Django 5.2.6 on 2025-09-25 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('question_id', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bkt_before', models.JSONField(default=dict, help_text='BKT parameters before interaction')),
                ('bkt_after', models.JSONField(default=dict, help_text='BKT parameters after interaction')),
                ('interaction_context', models.JSONField(default=dict, help_text='Additional interaction metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction History',
                'verbose_name_plural': 'Interaction Histories',
                'db_table': 'student_model_interaction_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentKnowledgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_skills_tracked', models.IntegerField(default=0)),
                ('mastered_skills_count', models.IntegerField(default=0)),
                ('average_mastery', models.FloatField(default=0.0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('correct_interactions', models.IntegerField(default=0)),
                ('learning_velocity', models.FloatField(default=0.0, help_text='Rate of skill acquisition')),
                ('dkt_hidden_state', models.JSONField(blank=True, default=list, help_text='DKT LSTM hidden state')),
                ('dkt_skill_predictions', models.JSONField(blank=True, default=list, help_text='DKT skill predictions')),
                ('dkt_last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Knowledge State',
                'verbose_name_plural': 'Student Knowledge States',
                'db_table': 'student_model_knowledge_state',
            },
        ),
        migrations.CreateModel(
            name='BKTSkillState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(help_text='Unique identifier for the skill', max_length=100)),
                ('P_L0', models.FloatField(default=0.1, help_text='Initial probability of knowing the skill')),
                ('P_T', models.FloatField(default=0.3, help_text='Learning (transition) rate')),
                ('P_G', models.FloatField(default=0.2, help_text='Guess rate')),
                ('P_S', models.FloatField(default=0.1, help_text='Slip rate')),
                ('P_L', models.FloatField(default=0.1, help_text='Current probability of knowing the skill')),
                ('interactions_count', models.IntegerField(default=0, help_text='Number of interactions with this skill')),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkt_skill_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BKT Skill State',
                'verbose_name_plural': 'BKT Skill States',
                'db_table': 'student_model_bkt_skill_state',
                'unique_together': {('user', 'skill_id')},
            },
        ),
    ]
