# Generated by Django 5.2.6 on 2025-09-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_adaptivequestion_level_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adaptivequestion',
            name='adaptive_qu_skill_i_3d0fcb_idx',
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='answer',
            field=models.CharField(choices=[('a', 'Option A'), ('b', 'Option B'), ('c', 'Option C'), ('d', 'Option D')], default='a', help_text='Correct option (a/b/c/d)', max_length=1),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='difficulty_level',
            field=models.CharField(choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='moderate', help_text='Difficulty from CSV', max_length=15),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='option_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='option_b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='option_c',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='option_d',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='subject',
            field=models.CharField(choices=[('quantitative_aptitude', 'Quantitative Aptitude'), ('logical_reasoning', 'Logical Reasoning'), ('data_interpretation', 'Data Interpretation'), ('verbal_ability', 'Verbal Ability')], default='quantitative_aptitude', help_text='Subject area', max_length=25),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags from CSV'),
        ),
        migrations.AlterField(
            model_name='adaptivequestion',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Legacy correct answer field'),
        ),
        migrations.AlterField(
            model_name='adaptivequestion',
            name='fundamental_type',
            field=models.CharField(blank=True, choices=[('listening', 'Listening'), ('grasping', 'Grasping'), ('retention', 'Retention'), ('application', 'Application')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adaptivequestion',
            name='level',
            field=models.IntegerField(default=1, help_text='Difficulty level (1=very_easy, 2=easy, 3=moderate, 4=difficult)'),
        ),
        migrations.AlterField(
            model_name='adaptivequestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('numerical', 'Numerical'), ('matching', 'Matching')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='adaptivequestion',
            name='skill_id',
            field=models.CharField(blank=True, help_text='Knowledge component/skill identifier', max_length=100),
        ),
        migrations.AddIndex(
            model_name='adaptivequestion',
            index=models.Index(fields=['subject', 'level'], name='adaptive_qu_subject_eba8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivequestion',
            index=models.Index(fields=['subject', 'difficulty_level'], name='adaptive_qu_subject_27a1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivequestion',
            index=models.Index(fields=['difficulty_level'], name='adaptive_qu_difficu_b62c23_idx'),
        ),
    ]
