# Generated by Django 5.2.6 on 2025-09-24 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_adaptivequestion_adaptive_qu_skill_i_3d0fcb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='ai_explanation_viewed',
            field=models.BooleanField(default=False, help_text='Whether AI explanation was viewed'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='assessment_mode',
            field=models.CharField(choices=[('EXAM', 'Exam Mode - No AI Help'), ('PRACTICE', 'Practice Mode - AI Assistance Available')], default='EXAM', help_text='Assessment mode: EXAM (no AI) or PRACTICE (AI help)', max_length=10),
        ),
        migrations.AddField(
            model_name='interaction',
            name='hints_requested',
            field=models.JSONField(blank=True, default=list, help_text='List of hints requested'),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('quantitative_aptitude', 'Quantitative Aptitude'), ('logical_reasoning', 'Logical Reasoning'), ('data_interpretation', 'Data Interpretation'), ('verbal_ability', 'Verbal Ability')], max_length=25)),
                ('assessment_mode', models.CharField(choices=[('EXAM', 'Exam Mode - No AI Help'), ('PRACTICE', 'Practice Mode - AI Assistance Available')], default='EXAM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Session'), ('COMPLETED', 'Completed Session'), ('ABANDONED', 'Abandoned Session')], default='ACTIVE', max_length=10)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('total_time_spent', models.FloatField(default=0.0, help_text='Total time in seconds')),
                ('current_difficulty', models.CharField(choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='very_easy', max_length=15)),
                ('initial_mastery_score', models.FloatField(default=0.0)),
                ('final_mastery_score', models.FloatField(default=0.0)),
                ('mastery_improvement', models.FloatField(default=0.0)),
                ('ai_analysis_requested', models.BooleanField(default=False)),
                ('ai_analysis_completed', models.BooleanField(default=False)),
                ('ai_analysis_data', models.JSONField(blank=True, default=dict, help_text='Stored AI analysis results')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'db_table': 'exam_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='exam_sessio_student_92f366_idx'), models.Index(fields=['subject', 'status'], name='exam_sessio_subject_dd7c4e_idx'), models.Index(fields=['assessment_mode', 'status'], name='exam_sessio_assessm_3231b5_idx'), models.Index(fields=['ai_analysis_requested', 'ai_analysis_completed'], name='exam_sessio_ai_anal_a99f54_idx')],
            },
        ),
    ]
