# Generated by Django 5.2.6 on 2025-09-25 16:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_improved_multi_student_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chapter',
            name='unique_chapter_per_subject',
        ),
        migrations.RemoveConstraint(
            model_name='dailystudystats',
            name='unique_daily_stats',
        ),
        migrations.RemoveConstraint(
            model_name='questionattempt',
            name='unique_question_attempt',
        ),
        migrations.RemoveConstraint(
            model_name='studentprogress',
            name='unique_student_subject_progress',
        ),
        migrations.RenameIndex(
            model_name='dailystudystats',
            new_name='daily_study_student_020357_idx',
            old_name='idx_daily_lookup',
        ),
        migrations.RenameIndex(
            model_name='questionattempt',
            new_name='question_at_session_ca1ab1_idx',
            old_name='idx_session_question_num',
        ),
        migrations.RenameIndex(
            model_name='questionattempt',
            new_name='question_at_student_f98edf_idx',
            old_name='idx_student_correct',
        ),
        migrations.RenameIndex(
            model_name='studentprogress',
            new_name='student_pro_student_4654de_idx',
            old_name='idx_progress_lookup',
        ),
        migrations.RenameIndex(
            model_name='studentsession',
            new_name='student_ses_student_d353b7_idx',
            old_name='idx_student_status',
        ),
        migrations.RenameIndex(
            model_name='studentsession',
            new_name='student_ses_subject_986b02_idx',
            old_name='idx_subject_type',
        ),
        migrations.RenameIndex(
            model_name='studentsession',
            new_name='student_ses_student_c0121c_idx',
            old_name='idx_student_subject_status',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='difficulty_levels_progressed',
            field=models.JSONField(default=list, help_text='Difficulty progressions today'),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='focus_duration_minutes',
            field=models.IntegerField(default=0, help_text='Continuous focused study time'),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='peak_performance_time',
            field=models.TimeField(blank=True, help_text='Time of best performance', null=True),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='personal_bests',
            field=models.JSONField(default=list, help_text='Personal bests achieved'),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='streaks_maintained',
            field=models.JSONField(default=dict, help_text='Streaks maintained'),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improved_daily_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='study_date',
            field=models.DateField(help_text='Date for these statistics'),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='subject_accuracy_rates',
            field=models.JSONField(default=dict, help_text='Accuracy per subject'),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='subject_question_counts',
            field=models.JSONField(default=dict, help_text='Questions per subject'),
        ),
        migrations.AlterField(
            model_name='dailystudystats',
            name='subject_time_distribution',
            field=models.JSONField(default=dict, help_text='Time spent per subject'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Attempt number if question repeated'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='bookmarked',
            field=models.BooleanField(default=False, help_text='Student bookmarked for review'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='confidence_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], help_text="Student's confidence level (1-5)", null=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='correct_answer',
            field=models.CharField(help_text='Correct answer for reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='hints_used',
            field=models.JSONField(default=list, help_text='List of hints used'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='interaction_data',
            field=models.JSONField(default=dict, help_text='Detailed interaction analytics'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='points_earned',
            field=models.FloatField(default=0.0, help_text='Points earned by student'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='question_number_in_session',
            field=models.IntegerField(help_text='Position of this question in the session'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='question_points',
            field=models.FloatField(default=1.0, help_text='Points assigned to this question'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='student_answer',
            field=models.CharField(blank=True, help_text="Student's answer (a/b/c/d or text)", max_length=10),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='student_feedback',
            field=models.TextField(blank=True, help_text='Optional student feedback on question'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='chapter_mastery_scores',
            field=models.JSONField(default=dict, help_text='Mastery scores per chapter'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='chapter_progress',
            field=models.JSONField(default=dict, help_text='Progress per chapter'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='difficulty_progression',
            field=models.JSONField(default=list, help_text='Historical difficulty progression'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='learning_velocity',
            field=models.FloatField(default=0.0, help_text='Questions per hour'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='mastery_score',
            field=models.FloatField(default=0.0, help_text='Overall mastery score (0-100)'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='performance_trend',
            field=models.JSONField(default=list, help_text='Performance trend over time'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='unlocked_chapters',
            field=models.JSONField(default=list, help_text='List of unlocked chapter IDs'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Specific chapter for chapter tests', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessment.chapter'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='current_question_number',
            field=models.IntegerField(default=0, help_text='Current question position in session'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='difficulty_adjustments',
            field=models.JSONField(default=list, help_text='History of difficulty adjustments'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='question_sequence',
            field=models.JSONField(default=list, help_text='Ordered list of question IDs'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session_config',
            field=models.JSONField(default=dict, help_text='Session-specific configuration'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='session_name',
            field=models.CharField(blank=True, help_text='Custom session name', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improved_study_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, help_text='Session time limit', null=True),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='total_questions_planned',
            field=models.IntegerField(default=10, help_text='Total questions planned for this session'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='dailystudystats',
            unique_together={('student', 'study_date')},
        ),
        migrations.AlterUniqueTogether(
            name='questionattempt',
            unique_together={('session', 'question', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'subject')},
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['subject', 'chapter_number'], name='chapters_subject_2dcb16_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['is_active'], name='chapters_is_acti_c509dc_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystudystats',
            index=models.Index(fields=['study_date'], name='daily_study_study_d_1ae15b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystudystats',
            index=models.Index(fields=['daily_accuracy_percentage'], name='daily_study_daily_a_41ad49_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['student', 'question'], name='question_at_student_56aa6b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['answer_status', 'created_at'], name='question_at_answer__321e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['session', 'created_at'], name='question_at_session_482c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['question', 'is_correct'], name='question_at_questio_612cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['subject', 'mastery_score'], name='student_pro_subject_bb53da_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['last_session_date'], name='student_pro_last_se_2f7915_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['current_mastery_level'], name='student_pro_current_43c75b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['session_start_time'], name='student_ses_session_f9fb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['status', 'updated_at'], name='student_ses_status_3b6b89_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='subjects_code_3f80fa_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='subjects_is_acti_960049_idx'),
        ),
    ]
