# Generated by Django 5.2.6 on 2025-09-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_remove_chapter_unique_chapter_per_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptivequestion',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Proper FK to Chapter table', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.chapter'),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='subject_fk',
            field=models.ForeignKey(blank=True, help_text='Proper FK to Subject table', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.subject'),
        ),
        migrations.AlterField(
            model_name='adaptivequestion',
            name='subject',
            field=models.CharField(choices=[('quantitative_aptitude', 'Quantitative Aptitude'), ('logical_reasoning', 'Logical Reasoning'), ('data_interpretation', 'Data Interpretation'), ('verbal_ability', 'Verbal Ability')], default='quantitative_aptitude', help_text='Legacy subject field - use subject_fk instead', max_length=25),
        ),
    ]
