# Generated by Django 5.2.6 on 2025-09-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_adaptivesubmission_adaptivesubmissionanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptivesubmission',
            name='chapter',
            field=models.CharField(blank=True, help_text='Chapter/topic within subject', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adaptivesubmission',
            name='subtopic',
            field=models.CharField(blank=True, help_text='Specific subtopic', max_length=100, null=True),
        ),
    ]
