# Generated by Django 5.2.6 on 2025-09-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_add_mastery_tracking'),
        ('assessment', '0010_alter_adaptivesubmission_chapter_and_more'),
    ]

    operations = [
    ]
