# Generated by Django 5.2.6 on 2025-09-26 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_merge_20250927_0407'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentmastery',
            name='unique_session_subject_chapter_mastery',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='current_mastery_score',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='mastery_achieved',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='mastery_achieved_at',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='mastery_threshold',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='session_analytics',
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='current_mastery_score',
            field=models.FloatField(default=0.0, help_text='Overall session mastery score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='mastery_achieved',
            field=models.BooleanField(default=False, help_text='Whether mastery has been achieved in this session'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='mastery_achieved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when mastery was achieved', null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='mastery_threshold',
            field=models.FloatField(default=0.8, help_text='Threshold for mastery achievement', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='session_analytics',
            field=models.JSONField(default=dict, help_text='Comprehensive session analytics for reporting'),
        ),
        migrations.AlterField(
            model_name='studentmastery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='studentmastery',
            unique_together={('student_session', 'subject', 'chapter')},
        ),
        migrations.AddIndex(
            model_name='studentmastery',
            index=models.Index(fields=['student_session', 'subject'], name='assessment__student_21bf90_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmastery',
            index=models.Index(fields=['subject', 'mastery_level'], name='assessment__subject_c289fc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmastery',
            index=models.Index(fields=['mastery_score'], name='assessment__mastery_358163_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmastery',
            index=models.Index(fields=['last_updated'], name='assessment__last_up_290278_idx'),
        ),
    ]
