# Generated by Django 5.2.6 on 2025-09-24 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRSCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ease_factor', models.FloatField(default=2.5, help_text='SM-2 ease factor (minimum 1.3)')),
                ('interval', models.IntegerField(default=1, help_text='Current interval in days')),
                ('repetition', models.IntegerField(default=0, help_text='Number of successful repetitions')),
                ('stage', models.CharField(choices=[('apprentice_1', 'Apprentice 1'), ('apprentice_2', 'Apprentice 2'), ('apprentice_3', 'Apprentice 3'), ('apprentice_4', 'Apprentice 4'), ('guru_1', 'Guru 1'), ('guru_2', 'Guru 2'), ('master', 'Master'), ('enlightened', 'Enlightened'), ('burned', 'Burned')], default='apprentice_1', max_length=20)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the card is due for review')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('correct_streak', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('is_suspended', models.BooleanField(default=False, help_text='Temporarily suspend reviews')),
                ('is_locked', models.BooleanField(default=False, help_text='Lock until prerequisites met')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to='assessment.adaptivequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SRS Card',
                'verbose_name_plural': 'SRS Cards',
                'db_table': 'srs_cards',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['student', 'due_date'], name='srs_cards_student_ac4c66_idx'), models.Index(fields=['stage', 'due_date'], name='srs_cards_stage_eb7949_idx'), models.Index(fields=['due_date'], name='srs_cards_due_dat_745228_idx')],
                'unique_together': {('student', 'question')},
            },
        ),
    ]
