# Generated by Django 5.2.6 on 2025-09-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_consecutive_correct_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='subject_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
